execute pathogen#infect()
call pathogen#helptags()
set relativenumber

" => Syntax highlighting
syntax enable
filetype plugin on

set nowrap

" => Colour scheme
set t_Co=256
set background=dark
colorscheme inkpot

" => Tab settings
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent

" => CtrlP
set runtimepath^=~/.vim/bundle/ctrlp.vim

" => Enable wildmenu
set wildmenu
set wildignore+=*.tmpl.php,*.tpl.php,*/tmp/*,*/public/shared/*,*.orig,*/.git/*,*/.vagrant/*,*/vendor/assets/*,*/public/system/*,*/log/*,*/doc/*,tags,*/public/assets/*

" => Don't backup files, it's all done by git
set nobackup
set nowb
set noswapfile

" => Always show status line
set laststatus=2

" " => Spell checker
map <leader>ss :setlocal spell!<cr>

" => Allow backspaces
set backspace=2

" => Highligh searches
set hlsearch
set incsearch

" => Show line numbers
set number

" => Emmet key map
let g:user_emmet_expandabbr_key = '<c-e>'
let g:use_emmet_complete_tag = 1

" => Window movement
map <C-J> <C-W>j<C-W>_
map <C-K> <C-W>k<C-W>_

autocmd BufNewFile,BufRead *.html.erb set filetype=html.eruby

"set tags=*/tags
